name: build
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.9.0
        with:
          gradle-project-path: ""
          gradle-build-module: |-
            :app
            :firstModule
            :secondModule
          sub-module-mode: 'INDIVIDUAL_DEEP'

      - name: Export Dependabot alerts
        uses: anyroadcom/dependabot-alert-export@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          org_name: 'ashutosh7107'
          repo_name: 'TestDependabotVulnerabilities'
          csv_path: data/vulnerability.csv

      - name: Fetch Dependabot alerts
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ashutosh7107/TestDependabotVulnerabilities/dependabot/alerts

      - name: Upload Vulnerability report
        uses: actions/upload-artifact@v3
        with:
          name: vulnerability_report
          path: data/vulnerability.csv
